modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/camcamcamcamcam/mindful-eating/issues"
license="https://github.com/camcamcamcamcam/mindful-eating/blob/master/LICENSE.txt"

[[mods]]
    modId="mindful_eating"
    version="1.1.0"
    logoFile="logo.png"
    authors="Cameron"
    credits="Rye, Gegy"
    displayName="Mindful Eating"
    description='''
    A mod that extends Diet. It rebalances food stats and gives subtle perks for different food groups.
    '''

[[dependencies.mindful_eating]]
    modId="forge"
    mandatory=true
    versionRange="[47.3.0,)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.mindful_eating]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.20.1,1.21)"
#    ordering="NONE"
#    side="BOTH"
#
#[[dependencies.mindful_eating]]
#    modId="blueprint"
#    mandatory=true
#    versionRange="[7.1.0,)"
#    ordering="AFTER"
#    side="BOTH"
#
#[[dependencies.mindful_eating]]
#    modId="diet"
#    mandatory=true
#    versionRange="[1.18.2-1.3.2.0,)"
#    ordering="AFTER"
#    side="BOTH"